#!/bin/bash

KERNELID=$(uname -r)
PRETTY_NAME=$(cat /etc/os-release | grep -i 'pretty_name' | cut -d '"' -f 2)
BOARD_VENDOR="Fundatrix"

TERM=linux toilet -f big $BOARD_VENDOR

printf '\nWelcome to \e[0;91m%s\e[m %s\n' "$PRETTY_NAME" "$KERNELID"
